import StyledComponentsRegistry from "./registry";
import { AiFillHome } from "react-icons/ai";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header, HeaderLink } from "./styled";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning={true}
      >
        <StyledComponentsRegistry>
          <Header>
            <HeaderLink href="/">
              <AiFillHome size={24} />
            </HeaderLink>
          </Header>
          {props.children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
